Automate OCS installation
afreen23/dev-setup pull request #1
Opened 2021-03-15 08:15 UTC by rexagod

Thank you for this repository! I couldn't stop myself from automating the workflow so I added a little something.

2021-03-15 13:22 UTC, afreen23 requested changes
Thanks for thinking to make it better :)

2021-03-15 13:22 UTC, afreen23 commented on README.md
> +
Instead of adding a whole function, lets add these two steps only  in step 1: Download the file.
```
wget https://raw.githubusercontent.com/afreen23/dev-setup/main/install-ocs.sh
 chmod +x install-ocs.sh
```
Actually this configuration is used by various people including doc writers and devs. Hence we dont want to be too specific. We must keep this generalized.
Agree that above two steps would be a good addition and seems missing currently.

2021-03-16 20:33 UTC, rexagod commented on README.md
> +
Fixed, PTAL.

2021-03-18 06:01 UTC, afreen23 approved these changes

2021-03-18 06:01 UTC, merged